algoritmo "exerc65"
// Função: Desenvolva um programa usando a estrutura para que mostre na tela a
seguinte contagem:
100 90 80 70 60 50 40 30 20 10 0 Acabou!
// Autor: Nathan Ferdinando
// Data: 04/10/2022
// Lista de Exercícios do Curso Em Video - Prof: Gustavo Guanabara

var
   C: inteiro

inicio
   para C <- 100 ate 0 passo -10 faca
      escreva (C)
   Fimpara
   escreval (" Acabou!")
fimalgoritmo