algoritmo "exerc38"
// Função: Escreva um programa que mostre na tela a seguinte contagem:
6 7 8 9 10 11 Acabou!
// Autor: Nathan Ferdinando
// Data: 10/10/2022
// Lista de Exercícios do Curso Em Video - Prof: Gustavo Guanabara

var
   Contador: Inteiro

inicio
   Contador <- 6
   enquanto (Contador <= 11) faca
      escreva (Contador)
      Contador <- Contador + 1
   Fimenquanto
   escreva (" Acabou!")
fimalgoritmo