algoritmo "exerc04"
// Função: Algoritimo para ler dois números inteiros e mostrar o somatório entre eles.
// Autor: Nathan Ferdinando
// Data: 10/10/2022
// Lista de Exercícios do Curso Em Video - Prof: Gustavo Guanabara

var
   v1, v2, Soma: inteiro

inicio
   escreva ("Digite um valor: ")
   leia (v1)
   escreva ("Digite outro valor: ")
   leia (v2)
   Soma <- v1 + v2
   escreva ("A soma entre ", v1, " e", v2, " é igual a ", Soma, ".")
fimalgoritmo