algoritmo "exerc41"
// Função: Desenvolva um programa que mostre na tela a seguinte contagem:
100 95 90 85 80 ... 0 Acabou!
// Autor: Nathan Ferdinando
// Data: 10/10/2022
// Lista de Exercícios do Curso Em Video - Prof: Gustavo Guanabara

var
   Cont: Inteiro

inicio
   Cont <- 100
   enquanto (Cont >= 80) faca
      escreva (Cont)
      Cont <- Cont - 5
   Fimenquanto
   escreva (" Acabou!")
fimalgoritmo